name: backtest-front
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: 'ap-northeast-2'

    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Generate Environment Variables File for Production
        run: |
          echo "REACT_APP_KAKAO_ID=$REACT_APP_KAKAO_ID" >> .env
          echo "REACT_APP_KAKAO_REDIRECT_URI=$REACT_APP_KAKAO_REDIRECT_URI" >> .env
        env:
          REACT_APP_KAKAO_ID: ${{ secrets.REACT_APP_KAKAO_ID }}
          REACT_APP_KAKAO_REDIRECT_URI: ${{ secrets.REACT_APP_KAKAO_REDIRECT_URI }}

      - name: yarn install
        run: yarn install

      - name: Build
        run: yarn build
        env:
          CI: "" # 경고를 에러로 보지 않게 함

      - name: Deploy S3 # Upload build file to S3
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://backtestv1

      - name: Invalidate cache CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
          PATHS: '/index.html'
        continue-on-error: true